### PR TITLE
Added BTM support

### LINKED ISSUE #109: Add support for BTM addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

### PR DESCRIPTION
**Pull request by surajsingla333**
## Issue number

closes #109 

## Description

The PR is related to the gitcoin bounty, https://gitcoin.co/issue/ensdomains/address-encoder/109/100023807,
As per the description, BTM support is added

## List of features added/changed

- Added BTM support using ethereum chain encoder/decoder

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

## Reference

- https://bytom.io/en/wallet/

## How Has This Been Tested?

- Using ethereum encoder to generate hex format of BTM addresses

## Screenshots (if appropriate):

Screenshot (3156)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
I have updated the Travis build to check that entries in the formats, tests, and README lists are in the correct order. Please check your PR and update it to maintain correct ordering in these lists.

**Comment by surajsingla333** [comment]
Thanks for the update, will check the PR and finish the updated builds

**Comment by surajsingla333** [comment]
Hey @Arachnid, the updates are done.

**Comment by makoto** [comment]
`https://bytom.io/en/wallet/` can you be more specific about where it says it's hex with checksum and where you found the test data? By looking at https://blockmeta.com/address/bm1qrym0et4w3nxlvysc6h6xy6rnll0p7hrr8rhs2e it looks like it has some prefix. If we can verify the address format, please also add the check logic.

**Comment by makoto** [comment]
Hi, please let me know if you want to continue working on this or you want me to pass on to someone else.

**Pull request closed without merging**
