### PR TITLE
Nuls address encoder

### LINKED ISSUE #199: Add support for NULS (NULS) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by surajsingla333**
##  Issue number

closes #199 

## Description

The PR is related to the gitcoin bounty, https://gitcoin.co/issue/ensdomains/address-encoder/199/100023886,
As per the description, NULS support is added

## List of features added/changed

-  Added NULS support using ethereum chain encoder/decoder

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

## How Has This Been Tested?

- Using ethereum encoder to generate hex format of NULS addresses

## Screenshots (if appropriate):

Screenshot (3162)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Review by makoto — CHANGES_REQUESTED** [review]
If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

**Comment by makoto** [comment]
Hello, any update on this?

**Comment by surajsingla333** [comment]
Hey, sorry for the delay. Look at it again today and update it.

**Comment by makoto** [comment]
Hi, please let me know how you are getting on with this along with others I commented on.
If you want to pass on to someone else, I can close the PRs as well.

**Comment by makoto** [comment]
Closing due to the lack of activity

**Pull request closed without merging**
