### PR TITLE
Add support for FIO addresses

### LINKED ISSUE #135: Add support for FIO addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by Echolon166**
## Issue number

Closes #135 

## Description

Add support for FIO addresses

## Reference to the specification

- [FIO public keys follows the same format as EOSIO, except the prefix is FIO instead of EOS](https://developers.fioprotocol.io/fio-protocol/accounts#privatepublic-keys:~:text=For%20those%20who%20have%20integrated%20EOSIO%2C,prefix%20is%20FIO%20instead%20of%20EOS.)
- [EOSIO implementation of ensdomains/crypto-addr-serialize](https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_public.js)
- https://github.com/fioprotocol/fio/blob/0a31c9aaab90e717a75746a7b73859c876d1dc7e/libraries/chain/include/eosio/chain/fioio/pubkey_validation.hpp#L22

## Reference to the test address.

- https://developers.fioprotocol.io/fio-protocol/accounts#privatepublic-keys:~:text=FIO7tkpmicyK2YWShSKef6B9XXqBN6LpDJo69oRDfhn67CEnj3L2G

## List of features added/changed

- Implement FIO encoder
- Implement FIO decoder

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.
- [x] I have specified correct coinTypes specified at [Slip 44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
- [x] I have provided the reference link to the specification I implemented.
- [x] I have provided enough explanation about how I provided the test address

### CODE REVIEW

**Comment by makoto** [comment]
Hi, thanks for the PR. You mentioned that FIO is identical to EOS (except "FIO" prefix) but the implementation seems quite different from EOS one. For example, yours use `ripemd160` checksum while EOS implementation is not.  Would you mind explaining the implementation difference?

**Comment by Echolon166** [comment]
> Hi, thanks for the PR. You mentioned that FIO is identical to EOS (except "FIO" prefix) but the implementation seems quite different from EOS one. For example, yours use `ripemd160` checksum while EOS implementation is not. Would you mind explaining the implementation difference?

Hi, both implementations should be the same. Their encoder/decoder implementation can be found [here](https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_utils.js). EOS also uses ripemd160 for checksum which can be seen in [#L20](https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_utils.js#L20) and in [#L44](https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_utils.js#L44).

**Comment by makoto** [comment]
Would it be possible to refactor checkEncode/decode function of EOS to be reusable with any other EOS forks like FIO?

checkEncode at https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_utils.js#L5 has more check logic than your own encoder (which has only checksum and bs58 encode) so I am guessing you can reuse the logic by refactoring

**Comment by Echolon166** [comment]
> Would it be possible to refactor checkEncode/decode function of EOS to be reusable with any other EOS forks like FIO?
> 
> checkEncode at https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/eos/key_utils.js#L5 has more check logic than your own encoder (which has only checksum and bs58 encode) so I am guessing you can reuse the logic by refactoring

Refactored current EOS encoder/decoder implementation to support multiple prefixes.
Also, converted all EOS forks which caught my eye to use the new implementation.

**Pull request merged**
