### PR TITLE
add support for AR

### PR DESCRIPTION
**Pull request by theperfectpunk**
## Issue number
Closes #133  

## Description

Add support for AR Encoder & Decoder

## List of features added/changed

- added arAddrEncoder method
- added arAddrDecoder method

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.
[https://github.com/satoshilabs/slips/blob/master/slip-0044.md](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
[https://docs.arweave.org/developers/server/http-api#addressing](https://docs.arweave.org/developers/server/http-api#addressing)
[https://github.com/ArweaveTeam/arweave-js/blob/master/src/common/lib/utils.ts](https://github.com/ArweaveTeam/arweave-js/blob/master/src/common/lib/utils.ts)

## How Has This Been Tested?

Created test case for jest and run test

## Screenshots (if appropriate):

Screenshot from 2020-10-07 00-54-37

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
I have updated the Travis build to check that entries in the formats, tests, and README lists are in the correct order. Please check your PR and update it to maintain correct ordering in these lists.

**Comment by theperfectpunk** [comment]
@Arachnid corrected the test ordering :thumbsup:

**Comment by makoto** [comment]
Hi, would you mind resolving conflicts?

**Review by makoto — CHANGES_REQUESTED** [review]
Merge conflicts

**Review by makoto — CHANGES_REQUESTED** [review]
Merge conflicts

**Comment by makoto** [comment]
Duplicate to https://github.com/ensdomains/address-encoder/pull/133

**Comment by theperfectpunk** [comment]
@makoto please give me some time to make changes

**Pull request closed without merging**
