### PR TITLE
Add support for STX (Blockstack) address

### PR DESCRIPTION
**Pull request by vinhbhn**
## Issue number

#295 

## Description

Add support for STX (Blockstack) address

## Reference to the specification

- https://github.com/blockstack/c32check/blob/master/src/address.ts#L37&&L59
- https://blockstackdocs.netlify.app/faqs/allfaqs#what-is-a-public-stacks-wallet-address

## Reference to the test address.

- https://github.com/blockstack/c32check/blob/master/tests/unitTests/src/index.ts#L461
- https://github.com/blockstack/c32check/blob/master/tests/unitTests/src/index.ts#L479
- https://github.com/blockstack/c32check/blob/master/tests/unitTests/src/index.ts#L500

## List of features added/changed

- STX encoder, decoder

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

## How much has the filesize increased?
21kB

## How Has This Been Tested?

STX address has the format: ``` S + P or M (p2pkh or p2sh version) + hex_payload + hex_checksum ```
``` hex_checksum = sha256(sha256(p2pkh or p2sh version + hex_payload)).substring(0, 4) ```
[Info](https://github.com/blockstack/c32check#how-it-works)

According to the 3 links I sent above, the hex_payload is a46ff88886c2ef9762d970b4d2c63678835bd39d which can be used both SP or SM addresses (if not using hex_checksum), so I decided to keep hex_payload and hex_checksum after that so I can use used for encoder 

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.
- [x] I have specified correct coinTypes specified at [Slip 44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
- [x] I have provided the reference link to the specification I implemented.
- [x] I have provided enough explanation about how I provided the test address

### CODE REVIEW

**Comment by makoto** [comment]
There is a size increase from 370k to 438k

**Comment by vinhbhn** [comment]
> There is a size increase from 370k to 438k

After editing, the file size increased by 21kb from 387kb to 408kb.

**Comment by vinhbhn** [comment]
Hey @makoto, can you review it?

**Comment by makoto** [comment]
Thanks for the contribution!

**Pull request merged**
