### PR TITLE
Ensdomains master Big max cleanup

### PR DESCRIPTION
**Pull request by x5engine**
went through everything and every detail.

When I npm run size I got 

1085093

image

### CODE REVIEW

**Comment by x5engine** [comment]
got 458358

**Comment by x5engine** [comment]
I got now 396922 @Arachnid

**Comment by Arachnid** [comment]
Please fix the build if you want your PRs considered.

**Comment by Arachnid** [comment]
Closed, as the build is still not passing.

**Comment by x5engine** [comment]
Npm run build runnned well 

And I can even screen cast it

**Comment by jay-dee7** [comment]
You'll have to rebase your branch from this master, as far as i remeber you had merge conflicts

**Comment by x5engine** [comment]
@jay-dee7 I rebased the branch in the second commit and after that, I had 3 or 4 commits to the PR which had my changes + your changes guys but I got no reward after 2 sleepless nights!

thanks so much guys

**Pull request closed without merging**
