### PR TITLE
Add support for BCN addresses

### LINKED ISSUE #195: Add support for Bytecoin (BCN) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by Echolon166**
## Issue number

Closes #195 

## Description

Add support for BCN addresses

## References
- [Bytecoin is powered by Cryptonote Technology](https://bytecoin.org/#pt_canvas:~:text=Bytecoin%20is%20powered%20by%20Cryptonote%20Technology)
- https://cryptonote.org/cns/cns007.txt

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
It looks like you're only partially decoding the address here - there's a checksum inside the base58 encoding, which you're not verifying.

**Comment by makoto** [comment]
Hello, any update on this?

**Comment by Echolon166** [comment]
Hi, I've tried to add the checksum, but there were some errors.
I'm guessing it uses a slightly different variation of base58, I will try to change it to use a common base58 library.

**Review by makoto — CHANGES_REQUESTED** [review]
https://github.com/ensdomains/address-encoder/pull/228#issuecomment-733227995

**Comment by makoto** [comment]
Hi, please let me know whether you want to continue working on this or you want to pass on to someone else.

**Comment by Echolon166** [comment]
Hello, I was unable to complete this task. Seems like my reference point cryptonote.org is down as well.
Closing this PR to not block the others from working on it.

**Pull request closed without merging**
