### PR TITLE
Add WAN support

### LINKED ISSUE #192: Add support for Wanchain (WAN) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by janus**
The PR would close out this issue
## Issue number
closes #192 

## Description
Add support for Wanchain (WAN) addresses in encoding which is checksum for address validity

## List of features added/changed
- wanToChecksumAddress
- isValidChecksumWanAddress
- wanChecksummedHexEncoder
- wanChecksummedHexDecoder

Reference // https://github.com/wanchain/go-wanchain/blob/develop/common/types.go

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify. Done

## How Has This Been Tested?
Added array of two items: one to be computed and another to be compare

## Checklist:
- [X ] My code follows the code style of this project.
- [ X] My code implements all the required features.

### CODE REVIEW

**Review by makoto — CHANGES_REQUESTED** [review]
Even though Wanchan started off as a fork of Ethereum, it looks like their checksum is different to how Ethereum does  https://wandevs.org/docs/difference-between-wanchain-and-ethereum

**Comment by janus** [comment]
This is what I found from the lib we used:
[1]https://github.com/ensdomains/crypto-addr-serialize/blob/master/lib/rskjs/rsk.js#L32
[2]https://wandevs.org/docs/difference-between-wanchain-and-ethereum/
From the links WAN tocheckSum and from Wan site [2]is same as the one found in [1]. [1] is from your repo.

**Comment by makoto** [comment]
> WAN tocheckSum and from Wan site [2]is same as the one found in [1]. [1] is from your repo

Interesting. It could be that Wanchain doc put Ethereum Wallet logic and Wanchain Wallet logic wrong.

Can you try to change your test data to `0x2eF088E183231C9bEA30d8430937D3A57b7327D4` which I got from https://www.wanscan.org/address/0x2eF088E183231C9bEA30d8430937D3A57b7327D4 and if it doesn't pass checksum, can you change it to work ?

I just used https://piyolab.github.io/sushiether/RunScrapboxCode/?web3=1.0.0-beta.33&code=https://scrapbox.io/api/code/sushiether/web3.js_-_Ethereum_%E3%81%AE%E3%82%A2%E3%83%89%E3%83%AC%E3%82%B9%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%82%B5%E3%83%A0%E4%BB%98%E3%81%8D%E3%82%A2%E3%83%89%E3%83%AC%E3%82%B9%E3%81%AB%E5%A4%89%E6%8F%9B%E3%81%99%E3%82%8B/demo.js to  checksum both Ethereum and Wanchain and Wanchain checksum seems not the same (`0x2Ef`) as opposed to (`0x2eF`)

Screenshot 2020-10-26 at 15 28 14

**Comment by janus** [comment]
Resolved

**Comment by makoto** [comment]
Please fix lint error https://travis-ci.com/github/ensdomains/address-encoder/jobs/409910705

**Comment by makoto** [comment]
File size `1149953` looks too big

**Comment by makoto** [comment]
Hi, are there any ways not to rely on `thor-devkit` but make use of existing dependencies ? For example at ` HASH.cry.keccak256(ndata);` we have both `Keccak` as dependencies. 

Let me know if you are still interested in working on. Otherwise, I will be closing this PR and reassign to someone else.

**Comment by janus** [comment]
> Hi, are there any ways not to rely on `thor-devkit` but make use of existing dependencies ? For example at ` HASH.cry.keccak256(ndata);` we have both `Keccak` as dependencies.
> 
> Let me know if you are still interested in working on. Otherwise, I will be closing this PR and reassign to someone else.

I would re-work it. Thanks

**Comment by janus** [comment]
@makoto  Job done. Review and close.

**Pull request merged**
