### PR TITLE
Add support for XMR addresses

### LINKED ISSUE #162: Add support for Monero (XMR) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

**We'd like to keep the encoding library as small as possible, so please be efficient in your use of space. This is particularly important for this bounty.**

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by Echolon166**
## Issue number

Closes #162 

## Description

Add support for XMR addresses

## List of features added/changed

- Implement XMR encoder
- Implement XMR decoder

## References
- https://web.getmonero.org/resources/moneropedia/address.html
- https://docs.rs/base58-monero/0.2.0/base58_monero/

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
This PR adds over 40k to the size of the library. Can you change it to use a common base58 library with the other coins that use this encoding, with a custom alphabet?

**Comment by Echolon166** [comment]
Unfortunately, using common base58 library is not possible with XMR as it is stated in [here](https://monerodocs.org/cryptography/base58/) and [here](https://docs.rs/base58-monero/0.2.0/base58_monero/).

XMR uses the same alphabet with common Base58 yet it encodes the blocks by 8-byte blocks(they get encoded all at once in Base58) and output is padded with "1"s(0 in Base58). The final block is padded as well to whatever would be the maximum size of this number of bytes encoded in Base58.

The final output is in the same format(with fixed size) yet the encoding technique is rather different.

**Comment by Echolon166** [comment]
@Arachnid I've made a few modifications to the @xmr-core/xmr-b58, and I guess I've managed to decrease the size to an acceptable amount. But I believe it is a lot of ugly code for the address-encoder itself.

Should I leave it as it is, if not, where/how would you prefer to store the encoding logic?

**Comment by makoto** [comment]
Thanks for the work. Can you let me know how much is the size difference? We are currently priortising low size PRs, but we will decide whether we should take in some large PRs.

Also, do you still need to commit package-lock.json if you ported the entire library into `ddress-encoder`?

**Comment by Echolon166** [comment]
I've managed to decrease the size from 40k to ~2.5k.
Package-lock.json should not be required since it doesn't add any new libraries into address-encoder.
I'm working on the lint errors.

**Comment by makoto** [comment]
What's your thought @Arachnid ? The master size used to be 750k but currently down to 457k after removing some dependency from other PR. This PR will increase from 457k to 459k, looks not too bad.

**Comment by makoto** [comment]
If we merge this in, can we reuse it for https://github.com/ensdomains/address-encoder/pull/211 and https://github.com/ensdomains/address-encoder/pull/226 so that they don't have to import `@xmr-core/xmr-b5` ?

**Comment by Echolon166** [comment]
> If we merge this in, can we reuse it for #211 and #226 so that they don't have to import `@xmr-core/xmr-b5` ?

Yes, I'm gonna update them once this PR gets merged.

**Comment by Echolon166** [comment]
I've updated them both to use this PR.

**Review by Arachnid — APPROVED** [review]

**Pull request merged**
