### PR TITLE
Added ABBC support

### LINKED ISSUE #107: Add support for ABBC addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

### PR DESCRIPTION
**Pull request by surajsingla333**
## Issue number

closes #107  

## Description

The PR is related to the gitcoin bounty, https://gitcoin.co/issue/ensdomains/address-encoder/107/100023808,
As per the description, ABBC support is added

## List of features added/changed

- Added ABBC support by extending EOS encoder and decoder and creating new function for the same.

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

## How Has This Been Tested?

- Using EOS encoder/decoder to generate hex format of ABBCaddresses

## Screenshots (if appropriate):

Screenshot (3159)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
I have updated the Travis build to check that entries in the formats, tests, and README lists are in the correct order. Please check your PR and update it to maintain correct ordering in these lists.

**Comment by surajsingla333** [comment]
Hey @Arachnid the changes have been made as per the updated tests.

**Comment by makoto** [comment]
`Added ABBC support by extending EOS encoder and decoder and creating new function for the same.` Can you give me the link of where you found this information and test dataset so that I can verify?

**Comment by makoto** [comment]
Hi, please let me know if you want to continue working on this or you want me to pass on to someone else.

**Comment by surajsingla333** [comment]
Hello @makoto, sorry for the delay I am not continuing the work on the issue.

**Pull request closed without merging**
