### PR TITLE
Added AIB support

### LINKED ISSUE #204: Add support for Advanced Internet Blocks (AIB) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by iRhonin**
Added AIB token

## Issue number

#204

## Description

- Added AIB encoder/decoder based on base58check

## List of features added/changed

- Added AIB encoder/decoder based on base58check

## Reference
- [AIB Built on top on Bitcoin Core](https://github.com/iobond/aib) (based on codes)
- [Tests](https://github.com/iobond/aib/blob/master/src/test/base58_tests.cpp)

## How Has This Been Tested?
- [Using library test cases](https://github.com/iobond/aib/blob/master/src/test/data/base58_keys_valid.json)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
Where are you sourcing the p2pk and p2pkh versions from?

**Comment by iRhonin** [comment]
By manually decoding an address from explorer.

> Where are you sourcing the p2pk and p2pkh versions from?

**Comment by makoto** [comment]
Hi, @iRhonin sorry for my lack of knowledge but can you elaborate a bit more about how you manually decoded?

I am guessing you looked up from [List of address prefixes](https://en.bitcoin.it/wiki/List_of_address_prefixes)

- letter `E` of `ETpFpzi5...` is decimal `33` which is hex `0x21`
- letter `V` of `VjGCUiF1p...` is decimal `71` which is hex `0x47`

Screenshot 2020-10-27 at 18 00 51
Screenshot 2020-10-27 at 18 01 21

However `E` could be between 32 - 34 and `V` could be between 69 - 72. How did you find out it's 33 and 71, not the other options?

**Comment by iRhonin** [comment]
> Hi, @iRhonin sorry for my lack of knowledge but can you elaborate a bit more about how you manually decoded?
> 
> I am guessing you looked up from [List of address prefixes](https://en.bitcoin.it/wiki/List_of_address_prefixes)
> 
> * letter `E` of `ETpFpzi5...` is decimal `33` which is hex `0x21`
> * letter `V` of `VjGCUiF1p...` is decimal `71` which is hex `0x47`
> 
> Screenshot 2020-10-27 at 18 00 51
> 
> Screenshot 2020-10-27 at 18 01 21
> 
> However `E` could be between 32 - 34 and `V` could be between 69 - 72. How did you find out it's 33 and 71, not the other options?
Hi @makoto 

I did this:
1. Register the token (AIB in here) in the library with the wrong prefixes
2. Add a test from [here](https://github.com/iobond/aib/blob/master/src/test/data/base58_keys_valid.json)
3. Run tests and see if it works, if not change the versions.

I but after what you said I dought it is correct or not,
I searched more in the repo and found this in [chainparam.cpp](https://github.com/iobond/aib/blob/master/src/chainparams.cpp): 

```
#define WTMINT_PUBKEY_ADDRESS 23 // Dec.
#define WTMINT_SCRPIT_ADDRESS 5 // Dec.

base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1,WTMINT_PUBKEY_ADDRESS);
base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1,WTMINT_SCRPIT_ADDRESS);
```

Also `WTMINT_SCRPIT_ADDRESS` is used for both mainnet and testnet :/ They don't have a for p2sh I think and used the same value for mainnet and testnet.

I checked explorer again and see addresses start with `A`, so `23` is correct for P2PK but did not find any address with the `3` prefix.

**Comment by makoto** [comment]
Thank you for your clarification

```Add a test from here```

Umm, can't find any testset starting `AJc4bPn` nor `76a9141f`. Do I have to further derive/decode from the test code? If so, could you state which test string did you derive from?

**Comment by iRhonin** [comment]
> Thank you for your clarification
> 
> `Add a test from here`
> 
> Umm, can't find any testset starting `AJc4bPn` nor `76a9141f`. Do I have to further derive/decode from the test code? If so, could you state which test string did you derive from and how?

Sorry, my bad, I forgot to update the PR's description:
`Add a test from here`:  it was before ths commit: https://github.com/ensdomains/address-encoder/pull/224/commits/a385bd85445b3e52182fd81dc6b21047c5ed8692
After your comment I cangend tests and versions.
I 98% sure they did not update the tests after changing the version byte and also they did not change the

**Comment by makoto** [comment]
Sorry for getting back to you late and thank you for your clarification

**Pull request merged**
