### PR TITLE
Added LUNA support, closes #113

### LINKED ISSUE #113: Add support for LUNA addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

### PR DESCRIPTION
**Pull request by iRhonin**
Added LUNA support, bech32 encoding.

## Issue number
closes #113.

## Description
Added bech32 support for LUNA (terra)

## List of features added/changed

- Bech32 Chain for LUNA

## Reference
- [Terra js sdk](https://github.com/terra-project/terra.js/blob/master/src/core/strings.ts)
- [Terra is built on top of Cosmos (ATOM) ](https://github.com/terra-project/core#what-is-terra) and cosmos uses bech32

## How Has This Been Tested?
- Using cosmos bech32 to create a decoded address 

## Screenshots (if appropriate):
image

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
I have updated the Travis build to check that entries in the formats, tests, and README lists are in the correct order. Please check your PR and update it to maintain correct ordering in these lists.

**Comment by makoto** [comment]
@iRhonin please resolve conflict. I can merge in as soon as conflict is resolved

**Comment by iRhonin** [comment]
@makoto done.

**Comment by makoto** [comment]
Sorry, I merged a lot so got conflicts again.

**Comment by iRhonin** [comment]
@makoto done.

**Pull request merged**
