### PR TITLE
Add XZC support

### LINKED ISSUE #169: Add support for Zcoin (XZC) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by ilanolkies**
## Issue number

Closes #169 

## Description

Adds support for ZCoin.

## List of features added/changed

- Added XZC support

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

Ref: https://explorer.zcoin.io/richlist

### CODE REVIEW

**Comment by makoto** [comment]
Same case as https://github.com/ensdomains/address-encoder/pull/187

**Comment by ilanolkies** [comment]
@makoto ref on their js lib https://github.com/firoorg/zcore-lib/blob/df21b096f38f57229cf6aa6be4c5b57b23e6ad0e/lib/address.js#L288

**Comment by makoto** [comment]
It looks to me Zcoin (now called Firo) is a fork of bitcoin.

I think you either have to add the validation like https://github.com/firoorg/firo-client/blob/master/src/lib/isValidAddress.ts#L21 or can reuse `bitcoinChain` function with correct   p2pkhVersions and p2shVersions

**Comment by makoto** [comment]
Hi, please let me know if you want to continue working on this or you want me to pass on to someone else.

**Comment by makoto** [comment]
Closing due to the lack of activity

**Pull request closed without merging**
