### PR TITLE
Add support for IRIS addresses

### LINKED ISSUE #165: Add support for IrisNet (IRIS) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by Echolon166**
## Issue number
Closes #165 

## Description

Add support for IRIS addresses

## References
- https://github.com/irisnet/irisnet-crypto/blob/23cf39ad9218c2a2c7f9584ffa5f4ee690e5ccaa/src/chains/iris/crypto.js#L75
- https://github.com/irisnet/irisnet-crypto/blob/23cf39ad9218c2a2c7f9584ffa5f4ee690e5ccaa/src/chains/iris/crypto.js#L179
- https://www.irisnet.org/docs/concepts/bech32-prefix.html#encoding

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Echolon166** [comment]
Updated PR fixes ordering & code.

**Comment by Echolon166** [comment]
Travis seems stuck creating/queueing tests yet if we check them one by one, each one of them passed with no issues

**Comment by Echolon166** [comment]
@makoto This PR was the first one among the IRIS PR's, please check both their dates. Resolved the existing conflicts.

**Comment by makoto** [comment]
Oh, you mean compared to https://github.com/ensdomains/address-encoder/pull/180 ? You are right. I will take yours.

**Pull request merged**
