### PR TITLE
Add STRAT support

### LINKED ISSUE #170: Add support for Stratis (STRAT) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by ilanolkies**
## Issue number

Closes #170 

## List of features added/changed

- Adds support for Stratis

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

Ref: https://chainz.cryptoid.info/strat/#!wallets

### CODE REVIEW

**Comment by makoto** [comment]
Hi, you referenced to explorer page but that does not prove that all you need is bs58 check. Can you point to official doc, code implementation or/and test cases?

**Comment by ilanolkies** [comment]
@makoto pretty same ref here: https://github.com/stratisproject/bitcore-lib-stratis/blob/master/lib/address.js#L345

**Comment by makoto** [comment]
Please also add other address format checks (length, network info, etc) which was implemented on the link you referenced to

**Comment by makoto** [comment]
Hi, please let me know if you want to continue working on this or you want me to pass on to someone else.

**Comment by makoto** [comment]
Closing due to the lack of activity

**Pull request closed without merging**
