### PR TITLE
Add support for CCXX addresses

### LINKED ISSUE #202: Add support for Counos X (CCXX) addresses in encoding library
Here is the encoding library: https://github.com/ensdomains/address-encoder

Example: https://github.com/ensdomains/address-encoder/pull/47/files

Discord for dev help: https://discord.com/invite/AskZbFx

Please provide a reference link so we can check you did the encoding correctly.

We'd like to keep the encoding library as small as possible, so please be efficient in your use of space.

We will likely be reviewing PRs and paying out bounties more or less on a weekly basis. No need to ping us to check your PR, we will definitely get to it.

Thanks for your help!

### PR DESCRIPTION
**Pull request by Echolon166**
## Issue number

Closes #202 

## Description

Add support for CCXX addresses

## References
- https://github.com/counos-platform/counos-X/blob/master/src/chainparams.cpp#L138
- [counos.io](https://www.counos.io/CounosX#ctl00_mainContent_ctl02_divContent:~:text=Counos%20X%20has%20been%20developed%20according%20to%20Litecoin%20version%2017.1.)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Echolon166** [comment]
Travis seems stuck creating/queueing tests yet if we check them one by one, each one of them passed with no issues

**Comment by makoto** [comment]
Hi, I resolved the conflict but the order of the coin is now wrong so the test is failing

**Comment by Echolon166** [comment]
The conflicted part is pushed on top of the CCXX in tests which broke the ordering. Will fix it.

**Comment by Echolon166** [comment]
> Hi, I resolved the conflict but the order of the coin is now wrong so the test is failing

@makoto Fixed.

**Pull request merged**
