### PR TITLE
Added LRG token Support

### PR DESCRIPTION
**Pull request by iRhonin**
Added LRG token

## Issue number

#205 

## Description

- Added LRG encoder/decoder based on base58check

## List of features added/changed

- Added LRG encoder/decoder based on base58check

## Reference
- [LRG Built on top on Bitcoin Core](https://github.com/largocoin/core) (based on codes)
- [Tests](https://github.com/largocoin/core/blob/master/src/test/key_tests.cpp#L57)

## How Has This Been Tested?
- [Using library test cases](https://github.com/largocoin/core/blob/master/src/test/data/base58_keys_valid.json)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.

### CODE REVIEW

**Comment by Arachnid** [comment]
Where are you sourcing the p2pk and p2pkh versions from?

**Comment by iRhonin** [comment]
> Where are you sourcing the p2pk and p2pkh versions from?

By manually decoding an address from explorer.

**Comment by makoto** [comment]
Same question as https://github.com/ensdomains/address-encoder/pull/224#issuecomment-717424592

**Comment by iRhonin** [comment]
> Same question as [#224 (comment)](https://github.com/ensdomains/address-encoder/pull/224#issuecomment-717424592)

I did the same as https://github.com/ensdomains/address-encoder/pull/224#issuecomment-717557063

[chainparams.cpp](https://github.com/largocoin/core/blob/master/src/chainparams.cpp)
Locks it is correct for this token unlike AIB.
```
        base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1, 30);
        base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1, 13);
```

**Comment by makoto** [comment]
Thank you for the clarification !

## NOTE to myself

Testnet have different addresses and it's not covered in this PR.

```
        base58Prefixes[PUBKEY_ADDRESS] = std::vector<unsigned char>(1, 139); // Testnet largo addresses start with 'x' or 'y'
        base58Prefixes[SCRIPT_ADDRESS] = std::vector<unsigned char>(1, 19);  // Testnet largo script addresses start with '8' or '9'
```

**Pull request merged**
