### PR TITLE
Added Kusama

### PR DESCRIPTION
**Pull request by Swader**
Added [Kusama](https://kusama.network).

### CODE REVIEW

**Comment by makoto** [comment]
Hi, @Swader . If we try to add DOT, can we use same `ksmAddrDecoder/Encoder` or do we need to modify?

**Comment by Swader** [comment]
Yes, that's because the addresses are interchangeable, see here for info about prefixes: https://wiki.polkadot.network/docs/en/learn-accounts#for-the-curious-how-prefixes-work

**Comment by makoto** [comment]
ah ok, where do we need to change to support DOT?

**Comment by Swader** [comment]
You need to just change the prefix being used in the encoder:

```js
function ksmAddrEncoder(data: Buffer): string {
  return polkadot.encodeAddress(data, 0);
}
```

The 0 prefix is for Polkadot. The 2 is for kusama. You can see a list of all prefixes here: https://github.com/ShiftNrg/substrate/blob/4c62403a3f8953ab0bd5f105e59b476730a5d193/primitives/core/src/crypto.rs#L431 - by just adding an encoder for all of them, you basically get support for all these chains OOTB.

**Comment by makoto** [comment]
Oh, that was super easy!

**Pull request merged**
