### PR TITLE
adding Nano conversion logic and test for MultiCoin

### PR DESCRIPTION
**Pull request by thelamer**
Please let me know if there is anything I missed here. 

Nano addresses are base32 hex conversions with a custom alphabet, and a 5 character blake2b checksum hash appended to the end. (the blakejs dep)

I tested this pretty thoroughly locally, the only thing I am not 100% on is error handling so I used throws like other functions. 

NodeJS example: 
```
const { formatsByName, formatsByCoinType } = require('@ensdomains/address-encoder');
const data = formatsByName['NANO'].decoder('nano_1qgkdadcbwn65sp95gr144fuc99tm5tn6gx9y8ow9bgaam6r5ixgtx19tw93');
console.log(data.toString('hex'));
const addr = formatsByCoinType[44].encoder(data);
console.log(addr); 
```

### CODE REVIEW

**Comment by thelamer** [comment]
FYI that build error is from using NodeJS 12.x as it is the new stable, I needed to perform all building and testing on Nodejs 10.x to get babel to install properly.

**Comment by Arachnid** [comment]
Can you please move the nano-base32 functionality into its own file, and rebase against current master?

**Comment by thelamer** [comment]
@Arachnid Let me know if that is what you were looking for, was not entirely sure on where to put the file so went with @types

**Comment by Arachnid** [comment]
@thelamer @types is for typescript type definitions. Ideal would be if you can add it to https://github.com/ensdomains/crypto-addr-serialize.

**Comment by thelamer** [comment]
Reference: 
https://github.com/ensdomains/crypto-addr-serialize/pull/7
Not 100% on it I am having trouble full looping with it as a module. I think I removed all the typescript specifics though.

**Pull request closed without merging**
