### PR TITLE
Add FTM Support

### PR DESCRIPTION
**Pull request by ibrahim1023**
## Description
Adding a support for FTM. FTM shares the same address structure as Ethereum addresses 

## Reference to the specification
https://fantom.foundation/fantom-faq/ (Is FTM an ERC20 token?)

## Reference to the test address.
https://ftmscan.com/address/0x314159265dD8dbb310642f98f50C066173C1259b

## List of features added/changed

- 
- 

NOTE: If you are adding new coin address support, please make sure to add a reference link to README so that reviewer can verify.

## How much has the filesize increased?

No change

## How Has This Been Tested?

Using the ETH Testcase

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code implements all the required features.
- [x] I have specified correct coinTypes specified at [Slip 44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
- [x] I have provided the reference link to the specification I implemented.
- [x] I have provided enough explanation about how I provided the test address

### CODE REVIEW

**Review by Arachnid — CHANGES_REQUESTED** [review]
Thank you. Can you please revert your changes to the pull request template, though?

**Comment by ibrahim1023** [comment]
Is it okay if i just create a new PR?

**Comment by Arachnid** [comment]
Of course!

**Comment by Arachnid** [comment]
Actually, no need to create a new one, we can squash-merge this one.

**Comment by Arachnid** [comment]
Can you please also revert the changes to package-lock?

**Pull request closed without merging**
